/** @type {import('tailwindcss').Config} */
  export default {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
      extend: {
        colors: {
          // These are now CSS variables controlled by base.css
          background: 'var(--color-background)',
          surface: 'var(--color-surface)',
          primary: 'var(--color-primary)',
          'text-main': 'var(--color-text-main)',
          'text-light': 'var(--color-text-light)',
          'red-50': 'var(--color-red-50)',
          'red-100': 'var(--color-red-100)',
          'red-200': 'var(--color-red-200)',
          'red-400': 'var(--color-red-400)',
          'red-600': 'var(--color-red-600)',
          'red-700': 'var(--color-red-700)',
          'red-800': 'var(--color-red-800)',
          'red-900': 'var(--color-red-900)',
          'orange-50': 'var(--color-orange-50)',
          'orange-100': 'var(--color-orange-100)',
          'orange-200': 'var(--color-orange-200)',
          'orange-400': 'var(--color-orange-400)',
          'orange-600': 'var(--color-orange-600)',
          'orange-700': 'var(--color-orange-700)',
          'orange-800': 'var(--color-orange-800)',
          'orange-900': 'var(--color-orange-900)',
          'green-50': 'var(--color-green-50)',
          'green-100': 'var(--color-green-100)',
          'green-200': 'var(--color-green-200)',
          'green-400': 'var(--color-green-400)',
          'green-600': 'var(--color-green-600)',
          'green-700': 'var(--color-green-700)',
          'green-800': 'var(--color-green-800)',
          'green-900': 'var(--color-green-900)',
          'purple-50': 'var(--color-purple-50)',
          'purple-100': 'var(--color-purple-100)',
          'purple-200': 'var(--color-purple-200)',
          'purple-400': 'var(--color-purple-400)',
          'purple-600': 'var(--color-purple-600)',
          'purple-700': 'var(--color-purple-700)',
          'purple-800': 'var(--color-purple-800)',
          'purple-900': 'var(--color-purple-900)',
          'pink-50': 'var(--color-pink-50)',
          'pink-100': 'var(--color-pink-100)',
          'pink-200': 'var(--color-pink-200)',
          'pink-400': 'var(--color-pink-400)',
          'pink-600': 'var(--color-pink-600)',
          'pink-700': 'var(--color-pink-700)',
          'pink-800': 'var(--color-pink-800)',
          'pink-900': 'var(--color-pink-900)',
        },
        animation: {
          'pulse-fast': 'pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        },
      },
    },
    plugins: [],
  }
